In [20]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
array = np.array([1,2,3,4])

print(np.sqrt(array))
print(np.pi*(array**2))

[1.         1.41421356 1.73205081 2.        ]
[ 3.14159265 12.56637061 28.27433388 50.26548246]


In [3]:
array2 = np.array([5,6,7,8])

print(array+array2)
print(array * array2)

[ 6  8 10 12]
[ 5 12 21 32]


In [4]:
scores = np.array([91,55,100,73,82,64])

print(scores == 100)
scores[scores< 65] = 0
print(scores)


[False False  True False False False]
[ 91   0 100  73  82   0]


In [5]:
Broad1 = np.array([[1,2,3,4,5,6,7,8,9,10]])
Broad2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(Broad1.shape)
print(Broad2.shape)

print(Broad1*Broad2)

(1, 10)
(10, 1)
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Built-in Functions

In [6]:
zeros = np.zeros((2,3,5))
print(zeros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [7]:
Ones = np.ones((2,3,5))
print(Ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [8]:
Full = np.full((2,3,5),3)
print(Full)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


In [9]:
eye = np.eye(3)
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
array = np.linspace(0,10,3)
print(array)

[ 0.  5. 10.]


In [11]:
array = np.array([[4, 2, 3, 1, 5],
                  [6, 7, 10, 9, 8]])

print(f'sum : {np.sum(array)}')
print(np.mean(array))
print(np.std(array))
print(np.var(array))
print(np.min(array))
print(np.max(array))
print(np.argmin(array))
print(np.argmax(array))

sum : 55
5.5
2.8722813232690143
8.25
1
10
3
7


In [12]:
ages = np.array([[21,17,19,23,26],
                [39,50,35,31,32]])

teenagers = ages[ages<20]
print(teenagers)

[17 19]


In [13]:
adults = np.where(ages<18,ages,0)
print(adults)

[[ 0 17  0  0  0]
 [ 0  0  0  0  0]]


### Random Fucntion